services:
  mariadb:
    image: mariadb:10.5.12
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080

  api:
    image: ghcr.io/beirlaenaaron/jetlist-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    env_file:
      - docker.ormconfig.env
    environment:
      NODE_ENV: Production
    volumes:
      - ./server/auth/service-account.json:/usr/app/auth/service-account.json

volumes:
  database: